### ISSUE TITLE
SoulShards2

### ISSUE THREAD

**Issue by DrZed** [ShadwDrgn/SoulShards#5]
ShardwDrgn since you don't seem to be alive anymore can we (HxCKDMS) have SoulShards2 we will keep everything as you wanted it to be.

**Comment by ShadwDrgn** [comment]
You're welcome to submit a pull request.

**Comment by DrZed** [comment]
You're alive. =0
I just wanted to update SS2 for 1.7.10 and 1.8.
Are you working on it?
I know SS2 isn't open source, but still I don't like the overpowered-ness of SSR.

**Comment by ShadwDrgn** [comment]
so fork, update, submit pull request. I'll probably accept it. I'll even update the thread with the newest version probably. That's why it's on github.

**Comment by DrZed** [comment]
Where is the source for Soul Shards 2? I'd fork it immediately if I saw it. I do believe it is a private repo.

**Comment by DrZed** [comment]
http://puu.sh/fy8Cj.png This is what I see.

**Comment by ShadwDrgn** [comment]
I'll have to see if i can find SS2 source. I was thinking this was SS2.

**Comment by ShadwDrgn** [comment]
closing this issue.

**Comment by DrZed** [comment]
did you lose your source code?
